# Generated by Django 3.2.4 on 2021-07-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_careerquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerQuestion',
        ),
    ]
